In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('Salaries new.csv')

In [3]:
data.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [4]:
data.tail()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148649,148650,Roy I Tillery,Custodian,0.0,0.0,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [5]:
data.shape

(148654, 13)

In [6]:
data.shape[0]   # shape returns a tuple.shape[0] refers to 1st element of this tuple

148654

In [7]:
data.shape[1]

13

In [8]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  str
 2   JobTitle          148654 non-null  str
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  str
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), str(3)
memory usage: 14.7 MB

## Check null values

In [9]:
data.isnull().sum()  # here sum will count the null values as isnull() returns true for null values

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                609
OvertimePay              4
OtherPay                 4
Benefits             36163
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              148654
dtype: int64

## Drop ID, Notes, Agency and status columns

In [10]:
data.columns

Index(['Id', 'EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year', 'Notes', 'Agency',
       'Status'],
      dtype='str')

In [11]:
data = data.drop(['Id','Notes','Agency','Status'], axis=1)  # along column
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

## Get overall statistics about the dataframe

In [12]:
data.describe(include='all')
# by default it works for numerical column 
# by using include=all it gives for all columns

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148654,148654,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000
unique,110811,2159,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Kevin Lee,Transit Operator,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,13,7036,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643
std,NaN,NaN,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538
min,NaN,NaN,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000
25%,NaN,NaN,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000
50%,NaN,NaN,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000
75%,NaN,NaN,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000
max,NaN,NaN,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000

## Find the occurence of the employee names (top 5)

In [13]:
data['EmployeeName'].value_counts().head()

EmployeeName
Kevin Lee       13
Steven Lee      11
William Wong    11
Richard Lee     11
KEVIN LEE        9
Name: count, dtype: int64

## Find the no. of unique job titles

In [14]:
len(data['JobTitle'].value_counts())

2159

In [15]:
# another method
data['JobTitle'].nunique()

2159

In [16]:
data['JobTitle'].unique()  # gives the unique values
len(data['JobTitle'].unique())

2159

## Total no. of job titles contain captain

In [17]:
len(data[data['JobTitle'].str.contains('captain', case=False)])

552

In [18]:
# another way
data[data['JobTitle'].str.contains('captain', case=False)].count()

EmployeeName        552
JobTitle            552
BasePay             551
OvertimePay         552
OtherPay            552
Benefits            411
TotalPay            552
TotalPayBenefits    552
Year                552
dtype: int64

## Display all the employee names from fire department

In [19]:
data.columns

Index(['EmployeeName', 'JobTitle', 'BasePay', 'OvertimePay', 'OtherPay',
       'Benefits', 'TotalPay', 'TotalPayBenefits', 'Year'],
      dtype='str')

In [20]:
data[data['JobTitle'].str.contains('fire department',case=False)]['EmployeeName']

4              PATRICK GARDNER
6                    ALSON LEE
8               MICHAEL MORRIS
9           JOANNE HAYES-WHITE
10               ARTHUR KENNEY
                  ...
32623             JAMES BARDEN
36162       Joanne Hayes-White
72926     Joanne M Hayes-White
102303          Robert E Evans
110535    Joanne M Hayes-White
Name: EmployeeName, Length: 226, dtype: str

## Find minimum, maximum and average basepay

In [21]:
data['BasePay'].describe()

count    148045.000000
mean      66325.448840
std       42764.635495
min        -166.010000
25%       33588.200000
50%       65007.450000
75%       94691.050000
max      319275.010000
Name: BasePay, dtype: float64

## Replace 'Not Provided' in EmployeeName column to NaN

In [22]:
data['EmployeeName']= data['EmployeeName'].replace('Not provided',np.nan)

## Drop the rows having 1 missing values

In [23]:
data=data.drop(data[data.isnull().sum(axis=1)==1].index,axis=0)
# we are using index to give list of indexes to drop function as 1st parameter

## Find job title of Albert Pardini

In [24]:
data[data['EmployeeName'] == 'Albert Pardini']['JobTitle']

36519    Captain 3
Name: JobTitle, dtype: str

## How much Albert Pardini make (include benefits)

In [25]:
data[data['EmployeeName'] == 'Albert Pardini']['TotalPayBenefits']

36519    253995.29
Name: TotalPayBenefits, dtype: float64

## Find top 5 most common jobs

In [26]:
data['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                6975
Special Nurse                   4382
Registered Nurse                3725
Public Svc Aide-Public Works    2514
Police Officer 3                2411
Name: count, dtype: int64

## Find Average BasePay of All Employee Per Year

In [27]:
data.groupby('Year')['BasePay'].mean()

Year
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

## Find Average BasePay of All Employee Per JobTitle

In [28]:
data.groupby('JobTitle')['BasePay'].mean()

JobTitle
ACPO,JuvP, Juv Prob (SFERS)       62290.780000
ASR Senior Office Specialist      60551.580167
ASR-Office Assistant              41253.471951
Account Clerk                     42372.579396
Accountant I                      61777.832500
                                      ...
Wire Rope Cable Maint Sprv        92751.746667
Worker's Comp Supervisor 1        68867.296429
Worker's Compensation Adjuster    72363.278784
X-Ray Laboratory Aide             46086.387100
Youth Comm Advisor                39077.957500
Name: BasePay, Length: 1110, dtype: float64

## Find Average BasePay of Employee Having Job Title ACCOUNTANT

In [29]:
data[data['JobTitle'].str.contains('Accountant')]['BasePay'].mean()

np.float64(75336.18288798921)

## Display Name of The Person Having The Highest BasePay

In [30]:
data[data['BasePay'] == data['BasePay'].max()]['EmployeeName']
# data['BasePay'] == data['BasePay']....this produces a boolean array which we can pass in data

72925    Gregory P Suhr
Name: EmployeeName, dtype: str